#!/usr/bin/env python

import os
import methods

Import('env')
Import('env_modules')

env_audio_stream_gdnative = env_modules.Clone()

env_audio_stream_gdnative.Append(CPPPATH=['#modules/gdnative/include/'])
env_audio_stream_gdnative.add_source_files(env.modules_sources, '*.cpp')

