#!/usr/bin/env python

import os
import methods

Import('env')
Import('env_modules')

env_packet_peer_gdnative = env_modules.Clone()

env_packet_peer_gdnative.Append(CPPPATH=['#modules/gdnative/include/'])
env_packet_peer_gdnative.add_source_files(env.modules_sources, '*.cpp')

